import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../services/api_client.dart';
import '../theme/app_colors.dart';

class FriendChallengeScreen extends StatefulWidget { const FriendChallengeScreen({super.key}); @override State<FriendChallengeScreen> createState() => _FriendChallengeScreenState(); }
class _FriendChallengeScreenState extends State<FriendChallengeScreen> {
  final _api = ApiClient(), _friend = TextEditingController(), _target = TextEditingController(), _message = TextEditingController(); String _exercise = 'Bench Press'; bool _sending = false; String? _result;
  @override void dispose() { _friend.dispose(); _target.dispose(); _message.dispose(); super.dispose(); }
  Future<void> _send() async { if (_friend.text.trim().isEmpty || _target.text.trim().isEmpty) return; setState(() { _sending = true; _result = null; }); try { await _api.challengeFriend({'recipientUsername': _friend.text.trim(), 'exercise': _exercise, 'exerciseKey': _exercise.toLowerCase().replaceAll(' ', '-'), 'target': _target.text.trim(), 'message': _message.text.trim()}); if (mounted) setState(() => _result = 'Challenge sent.'); } catch (_) { if (mounted) setState(() => _result = 'Unable to send this challenge.'); } finally { if (mounted) setState(() => _sending = false); } }
  @override Widget build(BuildContext context) => Scaffold(backgroundColor: AppColors.bg, appBar: AppBar(backgroundColor: AppColors.bg, leading: IconButton(onPressed: () => context.pop(), icon: const Icon(Icons.arrow_back)), title: const Text('Challenge a Friend', style: TextStyle(color: AppColors.textPrimary))), body: ListView(padding: const EdgeInsets.all(20), children: [const Text('Send a new challenge', style: TextStyle(color: AppColors.textPrimary, fontSize: 22, fontWeight: FontWeight.w800)), const SizedBox(height: 16), TextField(controller: _friend, style: const TextStyle(color: AppColors.textPrimary), decoration: const InputDecoration(labelText: 'Friend username or email')), const SizedBox(height: 12), DropdownButtonFormField<String>(value: _exercise, items: const ['Bench Press', 'Squat', 'Push Ups'].map((item) => DropdownMenuItem(value: item, child: Text(item))).toList(), onChanged: (value) => setState(() => _exercise = value ?? _exercise)), const SizedBox(height: 12), TextField(controller: _target, style: const TextStyle(color: AppColors.textPrimary), decoration: const InputDecoration(labelText: 'Target (e.g. 225 lbs)')), const SizedBox(height: 12), TextField(controller: _message, style: const TextStyle(color: AppColors.textPrimary), decoration: const InputDecoration(labelText: 'Message (optional)')), const SizedBox(height: 20), FilledButton(onPressed: _sending ? null : _send, child: Text(_sending ? 'Sending…' : 'Send challenge')), if (_result != null) Padding(padding: const EdgeInsets.only(top: 12), child: Text(_result!, style: TextStyle(color: _result == 'Challenge sent.' ? AppColors.success : AppColors.error))) ]));
}
