import { useEffect, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import { apiUrl } from "../../config";
import { authHeaders } from "../../api";
import { generatePosturePDF } from "../../utils/pdfGenerator";
import repUpLogo from "../../assets/repup-logo.jpeg";

function JointTable({ title, joints = [] }) { return <section style={{ marginBottom:16 }}><h4>{title}</h4>{joints.length ? <table style={{ width:"100%", borderCollapse:"collapse", fontSize:12 }}><thead><tr style={{ textAlign:"left", borderBottom:"2px solid #ddd" }}><th style={{ padding:6 }}>Joint</th><th style={{ padding:6 }}>Reading</th><th style={{ padding:6 }}>Status</th></tr></thead><tbody>{joints.map((joint, i) => <tr key={i}><td style={{ padding:6, borderBottom:"1px solid #ddd" }}>{joint.name || joint.joint || `Joint ${i + 1}`}</td><td style={{ padding:6, borderBottom:"1px solid #ddd" }}>{joint.label || (typeof joint.value === "number" ? `${joint.value.toFixed(1)}${joint.unit === "deg" ? "°" : joint.unit || ""}` : "—")}</td><td style={{ padding:6, borderBottom:"1px solid #ddd" }}>{joint.status || "—"}</td></tr>)}</tbody></table> : <p>No joint data recorded.</p>}</section>; }
export default function AssessmentReportPage(){const{assessmentId}=useParams();const[data,setData]=useState(null),[error,setError]=useState("");const reportRef=useRef(null);useEffect(()=>{const options={headers:authHeaders()};fetch(apiUrl(`trainer/assessments/${assessmentId}`),options).then(async r=>{const d=await r.json();if(!r.ok)throw new Error();return d}).then(setData).catch(()=>fetch(apiUrl("trainer/dashboard"),options).then(r=>r.json()).then(d=>{const assessment=d.assessments?.find(a=>String(a._id)===String(assessmentId));if(!assessment)throw new Error("Assessment not found.");setData({assessment,client:assessment.client})}).catch(e=>setError(e.message)))},[assessmentId]);if(error)return <main className="assessment-report-page"><p>{error}</p></main>;if(!data)return <main className="assessment-report-page"><p>Loading report…</p></main>;const{assessment:report,client}=data;const planes=report.planes||{},images=report.images||{},findings=report.findings||[],rec=report.recommendations||{avoid:[],focusOn:[]};return <main className="assessment-report-page"><div className="assessment-report-actions"><button onClick={()=>window.print()}>Print / Save PDF</button><button onClick={()=>generatePosturePDF(reportRef,client?.name)}>Download PDF</button></div><article ref={reportRef} className="assessment-report client-pdf-report"><header style={{display:"flex",alignItems:"center",gap:14,marginBottom:16,paddingBottom:14,borderBottom:"2px solid #111"}}><img src={repUpLogo} alt="RepUps" style={{width:60,height:60,borderRadius:"50%"}}/><div><b style={{fontSize:22}}>REP<span style={{color:"#7cc700"}}>UP</span></b><p>Your Personal AI Coach</p></div></header><h2>Full Biomechanical Posture Report</h2><div className="metric-card"><span>Composite Alignment Score</span><strong>{report.overallScore}/100</strong></div><div style={{display:"flex",gap:12,flexWrap:"wrap",margin:"20px 0"}}>{["front","side","back"].map(view=>images[view]&&<figure key={view}><img src={images[view]} alt={`${view} view`} style={{width:160,border:"1px solid #ddd",borderRadius:8}}/><figcaption>{view} View</figcaption></figure>)}</div>{["front","side","back","transverse"].map(view=><JointTable key={view} title={`${view[0].toUpperCase()+view.slice(1)} View Alignment`} joints={planes[view]?.joints}/>) }<section><h3>Findings</h3><ul>{findings.length?findings.map((f,i)=><li key={i}>{f}</li>):<li>No findings recorded.</li>}</ul></section><div style={{display:"flex",gap:24,flexWrap:"wrap"}}><section><h3>Avoid</h3><ul>{rec.avoid?.length?rec.avoid.map((f,i)=><li key={i}>{f}</li>):<li>Nothing flagged to avoid.</li>}</ul></section><section><h3>Focus On</h3><ul>{rec.focusOn?.length?rec.focusOn.map((f,i)=><li key={i}>{f}</li>):<li>No focus areas recorded.</li>}</ul></section></div></article></main>}
