import { useEffect, useState } from "react";
import { apiUrl } from "../../config";
import { authHeaders } from "../../api";
import { C, useBreakpoint } from "../theme";
import { Card, Avatar, Badge } from "../components";
const call=(path,options={})=>fetch(apiUrl(path),{...options,headers:{...authHeaders(),...(options.headers||{})}}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d});
export default function ClientsView({ onOpenClient }) {
 const [clients,setClients]=useState([]),[query,setQuery]=useState(""),[results,setResults]=useState([]),[loading,setLoading]=useState(true),[searching,setSearching]=useState(false),[error,setError]=useState(""); const {isMobile}=useBreakpoint();
 const load=()=>{setLoading(true);call("trainer/clients").then(d=>setClients(d.clients||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))}; useEffect(load,[]);
 const search=async e=>{e.preventDefault();if(query.trim().length<2)return;setSearching(true);setError("");try{setResults((await call(`trainer/client-search?q=${encodeURIComponent(query.trim())}`)).clients||[])}catch(err){setError(err.message)}finally{setSearching(false)}};
 const send=async id=>{try{await call("trainer/client-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientId:id})});setResults(x=>x.map(c=>c._id===id?{...c,requestStatus:"pending"}:c))}catch(err){setError(err.message)}};
 return <div><div style={{marginBottom:18}}><h2 style={{fontFamily:"'Barlow Condensed',sans-serif",fontSize:20,fontWeight:800,color:C.text}}>My Clients</h2><p style={{color:C.sub,fontSize:13}}>{clients.length} connected client{clients.length===1?"":"s"}</p></div><Card style={{padding:16,marginBottom:16}}><form onSubmit={search} style={{display:"flex",gap:8}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search client by email or username" style={{flex:1,background:C.card2,border:`1px solid ${C.border}`,borderRadius:8,color:C.text,padding:"10px 12px"}}/><button className="trainer-btn-primary" disabled={searching}>{searching?"Searching…":"Search"}</button></form>{results.map(c=><div key={c._id} style={{display:"flex",gap:10,alignItems:"center",paddingTop:12}}><Avatar initials={c.name?.slice(0,2).toUpperCase()} size={34}/><div style={{flex:1,color:C.text}}><b>{c.name}</b><div style={{fontSize:12,color:C.sub}}>{c.username?`@${c.username}`:c.email}</div></div>{c.requestStatus?<Badge color={c.requestStatus==="accepted"?C.lime:C.gold}>{c.requestStatus}</Badge>:<button onClick={()=>send(c._id)} className="trainer-btn-soft">Send Request</button>}</div>)}</Card>{error&&<p style={{color:C.red}}>{error}</p>}{loading?<p style={{color:C.sub}}>Loading clients…</p>:!clients.length?<Card style={{padding:20,color:C.sub}}>No clients yet. Search by email or username to send a connection request.</Card>:<div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"repeat(auto-fit,minmax(280px,1fr))",gap:12}}>{clients.map(c=><Card key={c._id} onClick={()=>onOpenClient(c._id)} style={{padding:16,cursor:"pointer"}}><div style={{display:"flex",gap:12,alignItems:"center"}}><Avatar initials={c.name?.slice(0,2).toUpperCase()} size={42}/><div><b style={{color:C.text}}>{c.name}</b><div style={{fontSize:12,color:C.sub}}>{c.email}</div><div style={{display:"flex",gap:6,marginTop:6}}>{c.goal&&<Badge>{c.goal}</Badge>}{c.fitnessLevel&&<Badge color={C.blue}>{c.fitnessLevel}</Badge>}</div></div></div></Card>)}</div>}</div>;
}
