import { useEffect, useState } from "react";
import { apiUrl } from "../../config";
import { authHeaders } from "../../api";
import { C } from "../theme";
import { Card } from "../components";

const newExercise = () => ({ name: "", sets: "3", reps: "10", rest: "60 sec", instructions: "" });
const newDay = () => ({ name: "Day", exercises: [newExercise()] });

export default function ProgramBuilderView() {
  const [clients, setClients] = useState(null), [clientId, setClientId] = useState(""), [name, setName] = useState(""), [goal, setGoal] = useState(""), [days, setDays] = useState([newDay()]), [status, setStatus] = useState("");
  useEffect(() => { fetch(apiUrl("trainer/clients"), { headers: authHeaders() }).then(r => r.json()).then(d => setClients(d.clients || [])).catch(() => setClients([])); }, []);
  const changeDay = (dayIndex, key, value) => setDays(items => items.map((day, i) => i === dayIndex ? { ...day, [key]: value } : day));
  const changeExercise = (dayIndex, exerciseIndex, key, value) => setDays(items => items.map((day, i) => i !== dayIndex ? day : { ...day, exercises: day.exercises.map((exercise, j) => j === exerciseIndex ? { ...exercise, [key]: value } : exercise) }));
  const save = async () => { if (!clientId || !name.trim() || days.some(day => day.exercises.some(exercise => !exercise.name.trim()))) return setStatus("Select a client and add a name for every exercise."); const response = await fetch(apiUrl("workout-plans"), { method: "POST", headers: { ...authHeaders(), "Content-Type": "application/json" }, body: JSON.stringify({ clientId, name, goal, status: "active", days }) }); const data = await response.json(); setStatus(response.ok ? "Plan assigned to the client." : data.error || "Unable to assign plan."); };
  if (clients === null) return <p style={{ color: C.sub }}>Loading clients…</p>;
  return <div><h2 style={{ color: C.text }}>Program Builder</h2><Card style={{ padding: 20 }}><select value={clientId} onChange={e => setClientId(e.target.value)} style={{ width: "100%", padding: 10, marginBottom: 10 }}><option value="">Select connected client</option>{clients.map(client => <option key={client._id} value={client._id}>{client.name}</option>)}</select><input value={name} onChange={e => setName(e.target.value)} placeholder="Plan name" style={{ width: "100%", boxSizing: "border-box", padding: 10, marginBottom: 10 }} /><input value={goal} onChange={e => setGoal(e.target.value)} placeholder="Goal (optional)" style={{ width: "100%", boxSizing: "border-box", padding: 10, marginBottom: 12 }} />{days.map((day, dayIndex) => <div key={dayIndex} style={{ padding: 12, marginBottom: 12, border: `1px solid ${C.border}`, borderRadius: 8 }}><input value={day.name} onChange={e => changeDay(dayIndex, "name", e.target.value)} placeholder="Workout day name" style={{ width: "100%", boxSizing: "border-box", padding: 8, marginBottom: 8 }} />{day.exercises.map((exercise, exerciseIndex) => <div key={exerciseIndex} style={{ display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr", gap: 6, marginBottom: 6 }}><input value={exercise.name} onChange={e => changeExercise(dayIndex, exerciseIndex, "name", e.target.value)} placeholder="Exercise" /><input value={exercise.sets} onChange={e => changeExercise(dayIndex, exerciseIndex, "sets", e.target.value)} placeholder="Sets" /><input value={exercise.reps} onChange={e => changeExercise(dayIndex, exerciseIndex, "reps", e.target.value)} placeholder="Reps" /><input value={exercise.rest} onChange={e => changeExercise(dayIndex, exerciseIndex, "rest", e.target.value)} placeholder="Rest" /></div>)}<button className="trainer-btn-soft" onClick={() => changeDay(dayIndex, "exercises", [...day.exercises, newExercise()])}>+ Exercise</button></div>)}<button className="trainer-btn-soft" onClick={() => setDays(items => [...items, newDay()])} style={{ marginRight: 8 }}>+ Workout Day</button><button className="trainer-btn-primary" onClick={save}>Save & Assign Plan</button>{status && <p style={{ color: C.sub }}>{status}</p>}</Card></div>;
}
