@@
 export const NAV_ITEMS = [
-  { id:"dashboard",    icon:"◈",  label:"Dashboard"     },
-  { id:"clients",      icon:"👥", label:"My Clients"    },
-  { id:"appointments", icon:"📅", label:"Appointments"  },
-  { id:"calendar",     icon:"🗓️", label:"Calendar"      },
-  { id:"messages",     icon:"💬", label:"Messages"      },
-  { id:"notifications",icon:"🔔", label:"Notifications" },
-  { id:"qna",          icon:"❓", label:"Q&A"           },
-  { id:"plans",        icon:"📋", label:"Workout Plans" },
-  { id:"assessments",  icon:"🧍", label:"Assessments"   },
-  { id:"reviews",      icon:"⭐", label:"Reviews"       },
+  { id:"dashboard",    icon:"◈",  label:"Dashboard"     },
+  { id:"appointments", icon:"📅", label:"Appointments"  },
+  { id:"calendar",     icon:"🗓️", label:"Calendar"      },
+  { id:"reviews",      icon:"⭐", label:"Reviews"       },
   { id:"earnings",     icon:"₹",  label:"Earnings"      },
   { id:"billing",      icon:"🧾", label:"Billing"       },
   { id:"profile",      icon:"🪪", label:"My Profile"    },
   { id:"settings",     icon:"⚙️", label:"Settings"      },
   { id:"help",         icon:"🛟", label:"Help & Support"},
 ];
