import React,{useState} from "react";
import {useNavigate} from "react-router-dom";
import {UserPlus,Send} from "lucide-react";
import {apiUrl} from "../../config";
import {authHeaders} from "../../api";
import {C,base,BottomNav,Top} from "./communityShared";
export default function ChallengeFriend(){
 const navigate=useNavigate(),[friend,setFriend]=useState(""),[exercise,setExercise]=useState("Bench Press"),[target,setTarget]=useState(""),[message,setMessage]=useState("");
 const [error,setError]=useState(""),[done,setDone]=useState("");
 const s={subtabs:{...base.card,display:"grid",gridTemplateColumns:"1fr 1fr",padding:4,marginBottom:12},sub:{height:38,border:0,borderRadius:8,background:"transparent",color:C.muted,fontSize:10,fontWeight:700},on:{background:C.lime,color:"#070905"},form:{...base.card,padding:12,marginBottom:10},title:{fontSize:16,fontWeight:800,display:"flex",alignItems:"center",gap:7,marginBottom:12},field:{marginBottom:9},label:{display:"block",color:C.muted,fontSize:8,marginBottom:5},input:{width:"100%",height:42,borderRadius:9,border:`1px solid ${C.border}`,background:"#080A0C",color:C.text,outline:0,padding:"0 10px",boxSizing:"border-box",fontSize:10},row:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8},send:{width:"100%",height:44,border:0,borderRadius:9,background:C.lime,color:"#070905",fontWeight:850,display:"flex",alignItems:"center",justifyContent:"center",gap:7,marginTop:6}};
 const submit=async()=>{try{const r=await fetch(apiUrl("community/friend-challenges"),{method:"POST",headers:{...authHeaders(),"Content-Type":"application/json"},body:JSON.stringify({recipientUsername:friend,exercise,exerciseKey:exercise.toLowerCase().replace(/\s+/g,"-"),target,message})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to send challenge.");setDone("Challenge sent.");setFriend("");setTarget("");}catch(e){setError(e.message)}};
 return <div style={base.page}><main style={base.shell}><Top navigate={navigate} active="challenges"/><section style={s.subtabs}><button style={s.sub} onClick={()=>navigate("/community/challenges")}>Open Challenges</button><button style={{...s.sub,...s.on}}>Challenge a Friend</button></section><section style={s.form}><div style={s.title}><UserPlus size={21} color={C.lime}/>Send a New Challenge</div>{error&&<p style={{color:C.blue,fontSize:9}}>{error}</p>}{done&&<p style={{color:C.lime,fontSize:9}}>{done}</p>}<div style={s.field}><label style={s.label}>SELECT A FRIEND</label><input style={s.input} value={friend} onChange={e=>setFriend(e.target.value)} placeholder="Registered name or email"/></div><div style={s.row}><div style={s.field}><label style={s.label}>EXERCISE</label><select value={exercise} onChange={e=>setExercise(e.target.value)} style={s.input}><option>Bench Press</option><option>Squat</option><option>Push Ups</option></select></div><div style={s.field}><label style={s.label}>TARGET</label><input style={s.input} value={target} onChange={e=>setTarget(e.target.value)} placeholder="e.g. 225 lbs"/></div></div><div style={s.field}><label style={s.label}>MESSAGE (OPTIONAL)</label><input style={s.input} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Add a message"/></div><button style={s.send} onClick={submit} disabled={!friend||!target}><Send size={16}/>Send Challenge</button></section><button style={{width:"100%",height:38,borderRadius:8,border:`1px solid ${C.blue}`,background:"transparent",color:C.blue,fontSize:9}} onClick={()=>navigate("/community/challenge-inbox")}>View Incoming & Pending Challenges</button></main><BottomNav navigate={navigate}/></div>;
}
