import React,{useEffect,useState} from "react";
import {useNavigate} from "react-router-dom";
import {apiUrl} from "../../config";
import {authHeaders} from "../../api";
import {C,base,BottomNav,Top} from "./communityShared";
const getUser=()=>{try{return JSON.parse(localStorage.getItem("user")||"{}")}catch{return{}}};
export default function ChallengeInbox(){
 const navigate=useNavigate(),user=getUser(),userId=user._id||user.id,[items,setItems]=useState([]),[error,setError]=useState("");
 const load=()=>userId&&fetch(apiUrl(`community/friend-challenges/${userId}`),{headers:authHeaders()}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to load challenges.");return d}).then(d=>setItems(d.challenges||[])).catch(e=>setError(e.message));
 useEffect(() => { load(); }, [userId]); const respond=(id,action)=>fetch(apiUrl(`community/friend-challenges/${id}/${action}`),{method:"POST",headers:authHeaders()}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to update challenge.");load()}).catch(e=>setError(e.message));
 const incoming=items.filter(x=>String(x.recipientId)===String(userId)&&x.status==="Pending"),pending=items.filter(x=>String(x.challengerId)===String(userId)), card={...base.card,padding:12,marginBottom:10}, avatar={width:42,height:42,borderRadius:"50%",border:`1px solid ${C.lime}`,background:"#171C20",display:"grid",placeItems:"center",color:C.lime,fontWeight:800};
 return <div style={base.page}><main style={base.shell}><Top navigate={navigate} active="challenges"/><div style={{...base.card,display:"grid",gridTemplateColumns:"1fr 1fr",padding:4,marginBottom:12}}><button style={{height:38,border:0,borderRadius:8,background:"transparent",color:C.muted,fontSize:10}} onClick={()=>navigate("/community/challenges")}>Open Challenges</button><button style={{height:38,border:0,borderRadius:8,background:C.lime,color:"#070905",fontSize:10,fontWeight:700}}>Challenge a Friend</button></div><h2 style={{fontSize:16}}>Incoming Challenge</h2>{error&&<p style={{color:C.blue,fontSize:9}}>{error}</p>}{incoming.map(x=><section key={x._id} style={card}><div style={{display:"grid",gridTemplateColumns:"42px 1fr",gap:9,alignItems:"center"}}><div style={avatar}>{x.challengerName.slice(0,2).toUpperCase()}</div><div><b style={{fontSize:12}}>{x.challengerName}</b><div style={{color:C.muted,fontSize:8}}>Challenges you to</div></div></div><h3 style={{fontSize:22,margin:"14px 0 6px"}}>{x.exercise}</h3><div style={{border:`1px solid ${C.border}`,borderRadius:8,padding:10,color:C.lime,fontSize:10}}>Target: {x.target}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:10}}><button onClick={()=>respond(x._id,"decline")} style={{height:40,border:`1px solid ${C.border}`,borderRadius:9,background:"transparent",color:C.text}}>Decline</button><button onClick={()=>respond(x._id,"accept")} style={{height:40,border:0,borderRadius:9,background:C.lime,color:"#070905",fontWeight:800}}>Accept</button></div></section>)}{!incoming.length&&<section style={{...card,color:C.muted,fontSize:10,textAlign:"center"}}>No incoming challenges.</section>}<h2 style={{fontSize:16,marginTop:18}}>Pending Invitations</h2>{pending.map(x=><section key={x._id} style={{...card,display:"grid",gridTemplateColumns:"42px 1fr auto",gap:9,alignItems:"center"}}><div style={avatar}>{x.recipientUsername.slice(0,2).toUpperCase()}</div><div><b style={{fontSize:10}}>{x.recipientUsername}</b><div style={{fontSize:8,color:C.muted}}>{x.exercise} • {x.status}</div></div><b style={{fontSize:10,color:C.lime}}>{x.target}</b></section>)}</main><BottomNav navigate={navigate}/></div>;
}
