import React,{useEffect,useState} from "react";
import {useNavigate} from "react-router-dom";
import {Target,Flame,Dumbbell} from "lucide-react";
import {apiUrl} from "../../config";
import {authHeaders} from "../../api";
import {C,base,BottomNav,Top} from "./communityShared";
const Icon=({i})=>i===0?<Target size={26}/>:i===1?<Flame size={26}/>:<Dumbbell size={26}/>;
export default function CommunityChallenges(){
 const navigate=useNavigate(),[items,setItems]=useState([]),[error,setError]=useState("");
 const load=()=>fetch(apiUrl("community/challenges"),{headers:authHeaders()}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load challenges.");return d}).then(d=>setItems(d.challenges||[])).catch(e=>setError(e.message));
 useEffect(() => { load(); }, []);
 const join=async id=>{try{const r=await fetch(apiUrl(`community/challenges/${id}/join`),{method:"POST",headers:authHeaders()});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to join challenge.");load();}catch(e){setError(e.message)}};
 const open=items.filter(x=>!x.joined),active=items.filter(x=>x.joined);
 const s={subtabs:{...base.card,display:"grid",gridTemplateColumns:"1fr 1fr",padding:4,marginBottom:12},sub:{height:38,border:0,borderRadius:8,background:"transparent",color:C.muted,fontSize:10,fontWeight:700},on:{color:C.lime,border:`1px solid ${C.lime}`},head:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8},stitle:{fontSize:15,fontWeight:800},view:{color:C.blue,fontSize:9},ccard:{...base.card,padding:10,marginBottom:8,display:"grid",gridTemplateColumns:"58px 1fr",gap:10},icon:{width:56,height:56,borderRadius:"50%",background:"rgba(200,255,61,.06)",border:`1px solid ${C.border}`,color:C.lime,display:"grid",placeItems:"center"},title:{fontSize:11,fontWeight:760},desc:{color:C.muted,fontSize:8.5,lineHeight:1.4,marginTop:4},meta:{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:8},xp:{color:C.lime,fontSize:9,fontWeight:800},join:{height:32,padding:"0 12px",border:0,borderRadius:8,background:C.lime,color:"#070905",fontSize:8.5,fontWeight:800},track:{height:5,borderRadius:999,background:"#2A3034",overflow:"hidden",marginTop:8},fill:{height:"100%",background:C.lime,borderRadius:999}};
 const Card=({item,i,joined})=><section style={s.ccard}><div style={s.icon}><Icon i={i}/></div><div><div style={{display:"flex",justifyContent:"space-between"}}><div style={s.title}>{item.title}</div>{joined&&<div style={{color:C.blue,fontSize:8}}>{item.daysLeft} days left</div>}</div><div style={s.desc}>{item.desc}</div>{joined&&<div style={s.track}><div style={{...s.fill,width:`${item.progress||0}%`}}/></div>}<div style={s.meta}><div style={s.xp}>XP {item.rewardXp||item.xp||0} • 👥 {item.participantCount||0}</div>{joined?<div style={{color:C.muted,fontSize:8}}>{item.progress||0}% complete</div>:<button style={s.join} onClick={()=>join(item._id)}>Join Challenge</button>}</div></div></section>;
 return <div style={base.page}><main style={base.shell}><Top navigate={navigate} active="challenges"/><section style={s.subtabs}><button style={{...s.sub,...s.on}}>Open Challenges</button><button style={s.sub} onClick={()=>navigate("/community/challenge-friend")}>Challenge a Friend</button></section>{error&&<p style={{color:C.blue,fontSize:10}}>{error}</p>}<div style={s.head}><div style={s.stitle}>Open Challenges</div><div style={s.view}>View all</div></div>{open.map((x,i)=><Card key={x._id} item={x} i={i}/>) }{open.length===0&&<p style={{color:C.muted,fontSize:10}}>No open challenges are available.</p>}<div style={{...s.head,marginTop:14}}><div style={s.stitle}>My Active Challenges</div><div style={s.view}>View all</div></div>{active.map((x,i)=><Card key={x._id} item={x} i={i} joined/>)}{active.length===0&&<p style={{color:C.muted,fontSize:10}}>You have not joined a challenge yet.</p>}</main><BottomNav navigate={navigate}/></div>;
}
