import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Globe2, Users } from "lucide-react";
import { apiUrl } from "../../config";
import { authHeaders } from "../../api";
import { C, base, BottomNav, Top } from "./communityShared";
const getUser=()=>{try{return JSON.parse(localStorage.getItem("user")||"{}")}catch{return {}}};
export default function CommunityLeaderboard(){
 const navigate=useNavigate(),[mode,setMode]=useState("global"),[data,setData]=useState([]),[error,setError]=useState("");
 useEffect(()=>{fetch(apiUrl("community/leaderboard"),{headers:authHeaders()}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load leaderboard.");return d}).then(d=>setData(d.leaderboard||[])).catch(e=>setError(e.message))},[]);
 const user=getUser(), shown=mode==="friends"?data.filter(x=>String(x.id)===String(user._id||user.id)):data, podium=[1,0,2];
 const s={switcher:{...base.card,display:"grid",gridTemplateColumns:"1fr 1fr",padding:4,marginBottom:10},sw:{height:38,border:0,borderRadius:8,background:"transparent",color:C.muted,fontSize:10,fontWeight:700},on:{background:C.lime,color:"#070905"},board:{...base.card,padding:12},btitle:{fontSize:14,fontWeight:800,display:"flex",alignItems:"center",gap:7},bsub:{color:C.muted,fontSize:9,marginTop:3},podium:{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,alignItems:"end",margin:"18px 0 12px"},pod:{textAlign:"center"},avatar:{width:54,height:54,borderRadius:"50%",background:"#171C20",margin:"0 auto 7px",display:"grid",placeItems:"center",border:`1px solid ${C.border}`,color:C.lime,fontWeight:800},first:{width:66,height:66,border:`2px solid ${C.lime}`},medal:{fontSize:18,marginBottom:5},name:{fontSize:10,fontWeight:760},xp:{color:C.lime,fontSize:10,marginTop:3,fontWeight:800},streak:{color:C.muted,fontSize:8,marginTop:3},row:{minHeight:54,display:"grid",gridTemplateColumns:"28px 42px 1fr auto auto",gap:7,alignItems:"center",borderTop:`1px solid ${C.border}`},rank:{textAlign:"center",fontSize:10,fontWeight:800},mini:{width:34,height:34,borderRadius:"50%",background:"#171C20",display:"grid",placeItems:"center",color:C.lime,fontSize:8,fontWeight:800}};
 return <div style={base.page}><main style={base.shell}><Top navigate={navigate} active="leaderboard"/><section style={s.switcher}><button style={{...s.sw,...(mode==="global"?s.on:{})}} onClick={()=>setMode("global")}>🌐 Global Leaderboard</button><button style={{...s.sw,...(mode==="friends"?s.on:{})}} onClick={()=>setMode("friends")}>👥 Friends Leaderboard</button></section><section style={s.board}><div style={s.btitle}>{mode==="global"?<Globe2 size={18}/>:<Users size={18}/>} {mode==="global"?"Global Leaderboard":"Friends Leaderboard"}</div><div style={s.bsub}>{mode==="global"?"Top athletes worldwide":"Your account only until friend following is added"}</div>{error&&<p style={{color:C.blue,fontSize:10}}>{error}</p>}<div style={s.podium}>{podium.map((index,slot)=>{const item=shown[index];if(!item)return <div key={slot}/>;return <div key={item.id} style={s.pod}><div style={s.medal}>{slot===1?"🥇":slot===0?"🥈":"🥉"}</div><div style={{...s.avatar,...(slot===1?s.first:{})}}>{item.avatar}</div><div style={s.name}>{item.name}</div><div style={s.xp}>{item.xp.toLocaleString()} XP</div><div style={s.streak}>🔥 {item.streak} workouts</div></div>})}</div>{shown.slice(3).map(item=><div key={item.id} style={s.row}><div style={s.rank}>{item.rank}</div><div style={s.mini}>{item.avatar}</div><div style={{fontSize:10,fontWeight:700}}>{item.name}</div><div style={s.xp}>{item.xp.toLocaleString()} XP</div><div style={s.streak}>🔥 {item.streak}</div></div>)}</section></main><BottomNav navigate={navigate}/></div>;
}
