import { useEffect, useMemo, useState } from "react";
import { apiUrl } from "../../config";
import { authHeaders } from "../../api";

const filters = ["All", "Strength", "Weight Loss", "Hypertrophy", "Mobility", "Cardio", "Sports"];
const previewGym = { _id: "preview-gym", name: "RepUps Fitness Studio", address: "Preview location", rating: 4.8, tags: ["Strength", "Cardio"], isPreview: true };
const request = (path, options = {}) => fetch(apiUrl(path), { ...options, headers: { ...authHeaders(), ...(options.headers || {}) } }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Request failed"); return data; });
const eventDate = (value) => { const date = new Date(value); return Number.isNaN(date) ? { month: "—", day: "—" } : { month: date.toLocaleString("en-US", { month: "short" }), day: date.getDate() }; };

export default function EventsGymsPage() {
  const [tab, setTab] = useState("gyms"), [filter, setFilter] = useState("All"), [search, setSearch] = useState(""), [gyms, setGyms] = useState(null), [events, setEvents] = useState(null), [message, setMessage] = useState("");
  useEffect(() => { Promise.all([request("gyms"), request("events")]).then(([gymData, eventData]) => { setGyms((gymData.gyms || []).map((gym) => ({ ...gym, address: gym.location || "Address unavailable", tags: gym.facilities || [] }))); setEvents((eventData.events || []).map((event) => ({ ...event, venue: event.location || "Venue unavailable", spotsLeft: event.capacity == null ? null : Math.max(event.capacity - (event.registrations || []).length, 0) }))); }).catch((error) => { setGyms([]); setEvents([]); setMessage(error.message); }); }, []);
  const matches = (item) => (filter === "All" || item.tags.includes(filter)) && (!search || item.name.toLowerCase().includes(search.toLowerCase()));
  const shownGyms = useMemo(() => gyms?.length === 0 ? [previewGym] : (gyms || []).filter(matches), [gyms, filter, search]);
  const shownEvents = useMemo(() => (events || []).filter((event) => matches({ ...event, tags: [] })), [events, filter, search]);
  const register = async (event) => { try { const data = await request(`events/${event._id}/register`, { method: "POST" }); setEvents((items) => items.map((item) => item._id === event._id ? { ...item, registrations: data.event.registrations, spotsLeft: item.spotsLeft == null ? null : Math.max(item.spotsLeft - 1, 0) } : item)); setMessage("You are registered for this event."); } catch (error) { setMessage(error.message); } };
  const loading = tab === "gyms" ? gyms === null : events === null;
  return <main className="explore-page"><div className="explore-inner"><header className="explore-header"><div><h2 className="explore-title">Nearby Gyms &amp; Events</h2><p className="explore-subtitle">Matched to your fitness goals</p></div><span className="explore-location-badge"><i />Near you</span></header><div className="explore-search-wrap"><span>⌕</span><input className="explore-search" placeholder={`Search ${tab}…`} value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="explore-filter-row">{filters.map((item) => <button key={item} className={`explore-filter-chip${filter === item ? " active" : ""}`} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="explore-tabs"><button className={`explore-tab${tab === "gyms" ? " active" : ""}`} onClick={() => setTab("gyms")}>Gyms</button><button className={`explore-tab${tab === "events" ? " active" : ""}`} onClick={() => setTab("events")}>Events</button></div>{message && <p className="explore-message">{message}</p>}{loading ? <div className="explore-empty">Loading…</div> : tab === "gyms" ? <><p className="explore-section-title">{shownGyms.length} gyms nearby</p><div className="explore-list">{shownGyms.map((gym) => <article key={gym._id} className="gym-card"><div className="gym-thumb">🏋️</div><div className="gym-body"><b>{gym.name}</b><p>{gym.address} {gym.rating != null && ` · ★ ${Number(gym.rating).toFixed(1)}`}</p><div className="gym-tags">{gym.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div><button className="explore-btn-primary" onClick={() => window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(gym.address || gym.name)}`, "_blank", "noopener,noreferrer")}>Get Directions</button><button className="explore-btn-ghost" onClick={() => setMessage(gym.isPreview ? "This is the single preview gym. Backend gyms replace it automatically." : gym.description || "No description available.")}>View Details</button></div></div></article>)}</div></> : <><p className="explore-section-title">{shownEvents.length} events coming up</p>{shownEvents.length ? <div className="explore-list">{shownEvents.map((event) => { const date = eventDate(event.startsAt); return <article key={event._id} className="event-card"><div className="event-date-block"><small>{date.month}</small><b>{date.day}</b></div><div className="event-body"><b>{event.name}</b><p>{event.venue}{event.startsAt && ` · ${new Date(event.startsAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}`}</p>{event.spotsLeft != null && <span>{event.spotsLeft} spots left</span>}<div><button className="explore-btn-primary" onClick={() => register(event)}>RSVP</button><button className="explore-btn-ghost" onClick={() => setMessage(event.description || "No description available.")}>Details</button></div></div></article>; })}</div> : <div className="explore-empty">No events match your filters.</div>}</>}</div></main>;
}
