import { useEffect, useState } from "react";
import { apiUrl } from "../../config";
import { authHeaders } from "../../api";
const box={background:"#161616",border:"1px solid #222",borderRadius:14,padding:18,marginBottom:12};
const request=(path,options={})=>fetch(apiUrl(path),{...options,headers:{...authHeaders(),...(options.headers||{})}}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d});
function Page({children}){return <main style={{minHeight:"100vh",background:"#0a0a0a",color:"#eee",padding:"28px 20px",fontFamily:"Barlow,sans-serif"}}><div style={{maxWidth:720,margin:"auto"}}>{children}</div></main>}
function PhotoUploader({user,onChange}){const[busy,setBusy]=useState(false),[error,setError]=useState("");const upload=async e=>{const file=e.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setError("Use a JPG, PNG, or WEBP image under 5MB.");return;}setBusy(true);setError("");try{const body=new FormData();body.append("photo",file);const data=await request("me/photo",{method:"POST",body});onChange(data.user);const saved=JSON.parse(localStorage.getItem("user")||"{}");localStorage.setItem("user",JSON.stringify({...saved,photoUrl:data.photoUrl}));}catch(err){setError(err.message)}finally{setBusy(false)}};return <div><div style={{width:84,height:84,borderRadius:"50%",background:user.photoUrl?`center/cover no-repeat url(${user.photoUrl})`:"#C8F135",color:"#000",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:800,fontSize:24}}>{!user.photoUrl&&user.name?.slice(0,2).toUpperCase()}</div><label style={{display:"inline-block",marginTop:8,color:"#C8F135",cursor:"pointer",fontSize:12}}>{busy?"Uploading…":"Change profile photo"}<input disabled={busy} onChange={upload} type="file" accept="image/jpeg,image/png,image/webp" style={{display:"none"}}/></label>{error&&<div style={{color:"#ff6666",fontSize:12}}>{error}</div>}</div>}
export function ClientProfile(){const[user,setUser]=useState(null),[error,setError]=useState("");useEffect(()=>{void request("me").then(d=>setUser(d.user)).catch(e=>setError(e.message));},[]);return <Page><h2>My Profile</h2>{error?<p>{error}</p>:!user?<p>Loading profile…</p>:<div style={box}><PhotoUploader user={user} onChange={setUser}/><h3>{user.name}</h3><p>{user.email}</p><p>Age: {user.age??"—"} · Goal: {user.goal||"—"}</p></div>}</Page>}
export function WorkoutPlans(){const[plans,setPlans]=useState(null),[error,setError]=useState("");useEffect(()=>{void request("workout-plans/me").then(d=>setPlans(d.plans)).catch(e=>setError(e.message));},[]);return <Page><h2>Workout Plan</h2>{error?<p>{error}</p>:!plans?<p>Loading plans…</p>:!plans.length?<div style={box}>Your trainer has not assigned a plan yet.</div>:plans.map(p=><div style={box} key={p._id}><h3>{p.name}</h3></div>)}</Page>}
export function ClientQuestions(){const[items,setItems]=useState(null);useEffect(()=>{void request("questions").then(d=>setItems(d.questions)).catch(()=>setItems([]));},[]);return <Page><h2>Q&A</h2>{!items?<p>Loading…</p>:items.map(q=><div style={box} key={q._id}>{q.question}<p>{q.answer||"Awaiting an answer"}</p></div>)}</Page>}
export function ClientNotifications(){const[items,setItems]=useState(null);useEffect(()=>{void request("notifications").then(d=>setItems(d.notifications)).catch(()=>setItems([]));},[]);return <Page><h2>Notifications</h2>{!items?<p>Loading…</p>:!items.length?<div style={box}>You have no notifications.</div>:items.map(n=><div style={box} key={n._id}><b>{n.title}</b><p>{n.body}</p></div>)}</Page>}
export function ConnectionRequests(){const[items,setItems]=useState(null);const load=()=>request("client/trainer-requests").then(d=>setItems(d.requests)).catch(()=>setItems([]));useEffect(()=>{void load();},[]);const answer=(id,status)=>request(`client/trainer-requests/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})}).then(load);return <Page><h2>Trainer Requests</h2>{!items?<p>Loading…</p>:items.map(r=><div style={box} key={r._id}><b>{r.trainer?.name||"Trainer"}</b>{r.status==="pending"&&<><button onClick={()=>answer(r._id,"accepted")}>Accept</button><button onClick={()=>answer(r._id,"rejected")}>Reject</button></>}</div>)}</Page>}
export function EventsGyms(){const[data,setData]=useState(null);useEffect(()=>{void Promise.all([request("events"),request("gyms")]).then(([events,gyms])=>setData({events:events.events,gyms:gyms.gyms})).catch(()=>setData({events:[],gyms:[]}));},[]);return <Page><h2>Events & Gyms</h2>{!data?<p>Loading…</p>:<><h3>Upcoming Events</h3>{data.events.length?data.events.map(e=><div style={box} key={e._id}>{e.name}</div>):<div style={box}>No upcoming events.</div>}<h3>Gyms</h3>{data.gyms.length?data.gyms.map(g=><div style={box} key={g._id}>{g.name}</div>):<div style={box}>No gyms listed yet.</div>}</>}</Page>}
