import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, CalendarDays, ChevronRight, Clock3, Dumbbell, FileText, Home, MapPin, MessageCircle, ScanLine, Star, User, Users, Video } from "lucide-react";
import { apiUrl } from "../../config";
import { authHeaders } from "../../api";

const C = { bg: "#030405", surface: "#090B0D", card: "#0D1012", border: "#242A2F", lime: "#C8FF3D", blue: "#1687FF", text: "#FFFFFF", muted: "#90989E" };
const initials = (name = "") => name.split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "?";
const request = (path) => fetch(apiUrl(path), { headers: authHeaders() }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Request failed"); return data; });
const asDate = (value) => value ? new Date(value).toLocaleString(undefined, { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "Session time pending";

export default function MyTrainerPage() {
  const navigate = useNavigate();
  const [trainer, setTrainer] = useState(null);
  const [plans, setPlans] = useState([]);
  const [bookings, setBookings] = useState([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([request("client/trainer"), request("workout-plans/me"), request("bookings")])
      .then(([trainerData, planData, bookingData]) => { setTrainer(trainerData.trainer || null); setPlans(planData.plans || []); setBookings(bookingData.bookings || []); })
      .catch((loadError) => setError(loadError.message || "Unable to load your trainer."))
      .finally(() => setLoading(false));
  }, []);

  const session = useMemo(() => bookings.filter((booking) => ["scheduled", "confirmed", "live"].includes(booking.status)).sort((a, b) => new Date(a.slotTime || a.scheduledAt) - new Date(b.slotTime || b.scheduledAt))[0] || null, [bookings]);
  const specializations = trainer?.specializations || trainer?.specialties || [];
  const details = {
    name: trainer?.name || "", title: trainer?.title || trainer?.trainingStyle || "Personal Trainer", photoUrl: trainer?.photoUrl || "",
    rating: Number(trainer?.rating || 0), reviews: trainer?.reviewCount || trainer?.reviewsCount || 0,
    location: trainer?.locationName || trainer?.location || "Location not listed", availability: trainer?.availabilityText || trainer?.availability || "Availability not listed",
    bio: trainer?.bio || "This trainer has not added a biography yet.", experience: trainer?.experience || trainer?.experienceYears || "—",
  };
  const openChat = () => navigate("/trainer-chat", { state: { trainerId: trainer?._id, trainer } });
  const openBooking = () => navigate("/trainer-chat", { state: { trainerId: trainer?._id, trainer, openBooking: true } });
  const navItems = [[Home, "Home", "/dashboard"], [Dumbbell, "Workout", "/session"], [ScanLine, "Assess", "/posture-assessment"], [MessageCircle, "Coach", "/client/my-trainer"], [User, "Profile", "/client/profile"]];

  if (loading) return <main style={{ minHeight: "100dvh", display: "grid", placeItems: "center", background: C.bg, color: C.muted, fontFamily: "var(--sans)" }}>Loading your trainer…</main>;
  if (error) return <main style={{ minHeight: "100dvh", display: "grid", placeItems: "center", padding: 24, background: C.bg, color: C.text, fontFamily: "var(--sans)" }}>{error}</main>;
  if (!trainer) return <main style={{ minHeight: "100dvh", display: "grid", placeItems: "center", padding: 28, background: C.bg, color: C.text, fontFamily: "var(--sans)", textAlign: "center" }}><div><h1 style={{ margin: 0, fontSize: 22 }}>My Trainer</h1><p style={{ color: C.muted, lineHeight: 1.6 }}>You are not connected with a trainer yet.</p><button type="button" onClick={() => navigate("/client/trainers")} style={{ border: 0, borderRadius: 10, background: C.lime, color: "#080a0a", padding: "12px 18px", fontWeight: 800, cursor: "pointer" }}>Find a trainer</button></div></main>;

  return <div style={{ minHeight: "100dvh", background: C.bg, color: C.text, fontFamily: "var(--sans, Inter, sans-serif)" }}>
    <main style={{ maxWidth: 430, margin: "0 auto", padding: "12px 14px calc(86px + env(safe-area-inset-bottom, 0px))" }}>
      <header style={{ display: "grid", gridTemplateColumns: "38px 1fr 38px", alignItems: "center", height: 42 }}><button type="button" aria-label="Back" onClick={() => navigate(-1)} style={{ border: 0, background: "transparent", color: C.text, cursor: "pointer" }}><ArrowLeft size={21} /></button><h1 style={{ margin: 0, textAlign: "center", fontSize: 16 }}>My Trainer</h1><span /></header>
      <section style={{ display: "grid", gridTemplateColumns: "126px 1fr", gap: 14, alignItems: "end", marginTop: 14 }}>
        <div style={{ height: 165, borderRadius: "18px 18px 5px 5px", overflow: "hidden", background: "linear-gradient(145deg,#1a2024,#080a0c)", display: "grid", placeItems: "center", border: `1px solid ${C.border}` }}>{details.photoUrl ? <img src={details.photoUrl} alt={details.name} style={{ width: "100%", height: "100%", objectFit: "cover" }} /> : <b style={{ color: C.lime, fontSize: 30 }}>{initials(details.name)}</b>}</div>
        <div style={{ paddingBottom: 8 }}><div style={{ display: "flex", alignItems: "center", gap: 5 }}><h2 style={{ margin: 0, fontSize: 22 }}>{details.name}</h2><span style={{ color: C.blue }}>◆</span></div><p style={{ margin: "5px 0", color: C.muted, fontSize: 11 }}>{details.title}</p><p style={{ margin: 0, color: "#e7e9e9", fontSize: 11 }}><Star size={13} fill="#ffd21f" color="#ffd21f" style={{ verticalAlign: "middle" }} /> {details.rating ? details.rating.toFixed(1) : "—"} <span style={{ color: C.muted }}>({details.reviews} reviews)</span></p><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", marginTop: 12 }}>{[[trainer.clientCount || "—", "Clients"], [details.rating || "—", "Rating"], [`${details.experience} ${String(details.experience).includes("year") ? "" : "yrs"}`, "Experience"]].map(([value, label]) => <div key={label} style={{ textAlign: "center", borderLeft: `1px solid ${C.border}` }}><b style={{ fontSize: 15 }}>{value}</b><small style={{ display: "block", color: C.muted, fontSize: 8 }}>{label}</small></div>)}</div></div>
      </section>
      <section style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, margin: "12px 0" }}><button type="button" onClick={openChat} style={{ height: 42, border: 0, borderRadius: 10, background: C.lime, color: "#070905", fontWeight: 800, cursor: "pointer" }}><MessageCircle size={15} style={{ verticalAlign: "middle", marginRight: 6 }} />Message</button><button type="button" onClick={openBooking} style={{ height: 42, border: `1px solid ${C.border}`, borderRadius: 10, background: C.surface, color: C.text, fontWeight: 700, cursor: "pointer" }}><CalendarDays size={15} style={{ verticalAlign: "middle", marginRight: 6 }} />Book Session</button></section>
      <section style={{ borderTop: `1px solid ${C.border}`, padding: "15px 2px" }}><h3 style={{ margin: 0, fontSize: 15 }}>About {details.name.split(" ")[0]}</h3><p style={{ margin: "8px 0", color: "#d4d8da", fontSize: 12, lineHeight: 1.55 }}>{details.bio}</p><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}><div style={{ padding: 10, background: C.surface, border: `1px solid ${C.border}`, borderRadius: 11 }}><Clock3 size={16} color={C.lime} /><b style={{ display: "block", color: C.lime, fontSize: 10, marginTop: 5 }}>Available</b><span style={{ display: "block", color: C.muted, fontSize: 10, marginTop: 3 }}>{details.availability}</span></div><div style={{ padding: 10, background: C.surface, border: `1px solid ${C.border}`, borderRadius: 11 }}><MapPin size={16} color={C.lime} /><b style={{ display: "block", color: C.lime, fontSize: 10, marginTop: 5 }}>Location</b><span style={{ display: "block", color: C.muted, fontSize: 10, marginTop: 3 }}>{details.location}</span></div></div></section>
      {specializations.length > 0 && <section style={{ borderTop: `1px solid ${C.border}`, padding: "15px 2px" }}><h3 style={{ margin: 0, fontSize: 15 }}>Specializations</h3><div style={{ display: "flex", flexWrap: "wrap", gap: 7, marginTop: 10 }}>{specializations.map((specialty) => <span key={specialty.name || specialty} style={{ border: `1px solid ${C.border}`, background: C.surface, borderRadius: 9, padding: "7px 9px", fontSize: 10 }}><Dumbbell size={12} color={C.lime} style={{ verticalAlign: "middle", marginRight: 4 }} />{specialty.name || specialty}</span>)}</div></section>}
      <section style={{ borderTop: `1px solid ${C.border}`, padding: "15px 2px" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><h3 style={{ margin: 0, fontSize: 15 }}>Assigned Plans</h3><button type="button" onClick={() => navigate("/client/workout-plan")} style={{ color: C.lime, border: 0, background: "transparent", cursor: "pointer", fontSize: 10 }}>View all</button></div>{plans.length ? plans.map((plan) => <button key={plan._id} type="button" onClick={() => navigate("/client/workout-plan")} style={{ width: "100%", marginTop: 9, display: "grid", gridTemplateColumns: "50px 1fr 18px", gap: 10, alignItems: "center", textAlign: "left", border: `1px solid ${C.border}`, background: C.surface, color: C.text, borderRadius: 12, padding: 9, cursor: "pointer" }}><div style={{ height: 48, borderRadius: 9, display: "grid", placeItems: "center", background: "#11181d", color: C.lime }}><Dumbbell size={22} /></div><div><b style={{ fontSize: 12 }}>{plan.name || "Workout plan"}</b><span style={{ display: "block", marginTop: 4, color: C.muted, fontSize: 10 }}>{plan.days?.length || plan.daysPerWeek || "—"} days per week</span></div><ChevronRight size={17} color={C.muted} /></button>) : <p style={{ color: C.muted, fontSize: 11 }}>No assigned plans yet.</p>}</section>
      <section style={{ borderTop: `1px solid ${C.border}`, padding: "15px 2px" }}><h3 style={{ margin: "0 0 9px", fontSize: 15 }}>Upcoming Session</h3>{session ? <div style={{ display: "grid", gridTemplateColumns: "44px 1fr auto", gap: 9, alignItems: "center", padding: 10, background: C.surface, border: `1px solid ${C.border}`, borderRadius: 12 }}><div style={{ display: "grid", placeItems: "center", width: 42, height: 42, color: C.lime, background: "#172212", borderRadius: 9 }}><CalendarDays size={20} /></div><div><b style={{ fontSize: 12 }}>1:1 Coaching Session</b><span style={{ display: "block", marginTop: 3, color: C.muted, fontSize: 10 }}>{asDate(session.slotTime || session.scheduledAt)}</span><span style={{ color: C.muted, fontSize: 10 }}><Video size={11} style={{ verticalAlign: "middle" }} /> In-app video session</span></div>{["confirmed", "live"].includes(session.status) && <button type="button" onClick={openChat} style={{ border: `1px solid ${C.blue}`, background: "transparent", color: C.blue, borderRadius: 8, padding: "8px 9px", fontSize: 9, cursor: "pointer" }}>Join</button>}</div> : <p style={{ color: C.muted, fontSize: 11 }}>No upcoming sessions.</p>}</section>
      <section style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", marginTop: 10, border: `1px solid ${C.border}`, background: C.surface, borderRadius: 12, overflow: "hidden" }}>{[[Users, trainer.clientCount || "—", "Clients"], [Star, details.rating || "—", "Rating"], [CalendarDays, plans.length, "Plans"]].map(([Icon, value, label]) => <div key={label} style={{ textAlign: "center", padding: 11, borderLeft: `1px solid ${C.border}` }}><Icon size={17} color={C.blue} /><b style={{ display: "block", fontSize: 14, marginTop: 4 }}>{value}</b><small style={{ color: C.muted, fontSize: 8 }}>{label}</small></div>)}</section>
    </main>
    <nav style={{ position: "fixed", zIndex: 30, bottom: 0, left: "50%", transform: "translateX(-50%)", width: "min(100%, 430px)", display: "grid", gridTemplateColumns: "repeat(5,1fr)", height: "calc(67px + env(safe-area-inset-bottom, 0px))", paddingBottom: "env(safe-area-inset-bottom, 0px)", background: "#050607", borderTop: `1px solid ${C.border}` }}>{navItems.map(([Icon, label, path]) => { const active = path === "/client/my-trainer"; return <button key={path} type="button" onClick={() => navigate(path)} style={{ border: 0, background: "transparent", color: active ? C.lime : C.muted, cursor: "pointer", display: "grid", placeItems: "center", alignContent: "center", gap: 3, fontSize: 9 }}><Icon size={18} /><span>{label}</span></button>; })}</nav>
  </div>;
}
