import { useEffect, useState } from "react";
import { apiUrl } from "../../config";
import { authHeaders } from "../../api";
const MOCK_PLAN = { _id: "preview-plan", name: "Strength Foundations", active: true, trainerName: "Alex Morgan", description: "A balanced three-day plan to build strength and consistency.", completedDays: 1, days: [{ label: "Day 1", focus: "Full Body", exercises: [{ name: "Barbell Squat", muscleGroup: "Quads", equipment: "Barbell", sets: 4, reps: 8, restSeconds: 90 }, { name: "Bench Press", muscleGroup: "Chest", equipment: "Barbell", sets: 3, reps: 10, restSeconds: 60 }] }, { label: "Day 2", focus: "Upper Body", exercises: [{ name: "Lat Pulldown", muscleGroup: "Back", equipment: "Cable", sets: 3, reps: 12, restSeconds: 60 }] }, { label: "Day 3", isRestDay: true, exercises: [] }] };
function Day({ day, index }) { const [open, setOpen] = useState(index === 0); return <div className={`wp-day${open ? " open" : ""}`}><button className="wp-day-header" onClick={() => setOpen(!open)}><b>{day.label || day.name || `Day ${index + 1}`}</b>{day.focus && <span>{day.focus}</span>}<em>{open ? "⌃" : "⌄"}</em></button>{open && <div className="wp-day-body">{day.isRestDay ? <p>Recovery day — no exercises scheduled.</p> : day.exercises.map((exercise, i) => <div className="wp-exercise-row" key={i}><small>{String(i + 1).padStart(2, "0")}</small><div><b>{exercise.name}</b><p>{[exercise.muscleGroup, exercise.equipment].filter(Boolean).join(" · ")}</p></div><strong>{exercise.sets}×{exercise.reps}<small>{exercise.rest || (exercise.restSeconds ? `${exercise.restSeconds}s` : "—")} rest</small></strong></div>)}</div>}</div>; }
export default function WorkoutPlanPage() {
  const [plans, setPlans] = useState(null); const [error, setError] = useState("");
  useEffect(() => { fetch(apiUrl("workout-plans/me"), { headers: authHeaders() }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Request failed"); return data; }).then(data => setPlans(data.plans)).catch(err => setError(err.message)); }, []);
  const visiblePlans = plans?.length ? plans : [MOCK_PLAN];
  return <main className="workout-plan-page"><div className="wp-inner"><h2>Workout Plan</h2><p className="wp-subtitle">Assigned by your trainer</p>{error ? <p>{error}</p> : !plans ? <p>Loading plans…</p> : <>{!plans.length && <p className="wp-preview-note">Showing a preview plan until your trainer assigns one.</p>}{visiblePlans.map((plan) => <section className="wp-plan-card" key={plan._id}><header><div><h3>{plan.name}</h3><p>{plan.trainerName} · {plan.days.length} days/week</p></div><span>Active</span></header><p>{plan.description}</p><div className="wp-progress"><i style={{ width: `${Math.round((plan.completedDays / plan.days.length) * 100)}%` }} /></div><div>{plan.days.map((day, index) => <Day day={day} index={index} key={index} />)}</div></section>)}</>}</div></main>;
}
